# -*- coding: utf-8 -*-
"""train_mask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FxU5djLuq5Tftp4kcNL8iRjLg0oxbZZi
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

from yolov5 import utils
display = utils.notebook_init()

!unzip '/content/data.zip' -d '/content/'

!python train.py --img 416 --batch 3 --epochs 40 --data custom.yaml --weights yolov5s.pt --cache